In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)

print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array(
    [[[1, 2], 
     [3, 4]],
     [[5, 6],
     [7, 8]]
     ]
)

print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
zeros = np.zeros(5) # 5개
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones((2, 3)) # 2행 3열
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
range_arr = np.arange(1, 10, 2)
print(range_arr)

[1 3 5 7 9]


In [12]:
# 데이터 타입
정수 = np.array([1, 2, 3, 4, 5])
정수.dtype

dtype('int64')

In [13]:
실수 = np.array([1.2, 3.4, 5.6])
실수.dtype

dtype('float64')

In [19]:
# 배열 속성
arr1 = np.array([1, 2, 3, 4])
arr1.shape

(4,)

In [18]:
arr2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
arr2.shape

(2, 3)

In [16]:
arr3 = np.array(
    [[[1, 2], 
     [3, 4]],
     [[5, 6],
     [7, 8]]
     ]
)
arr3.shape

(2, 2, 2)

In [ ]:
# ndim (차원을 알려주는)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
# size - 배열의 총 요소 수를 알려준다
arr1 = np.size([1, 2, 3, 4])
print(arr1)

4


In [24]:
arr3_size = np.size(arr3)
print(arr3_size)

8
