In [1]:
# reshape
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [ ]:
reshaped = arr.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr)

[1 2 3 4 5 6]


In [10]:
print(reshaped.shape)
print(reshaped)

NameError: name 'reshaped' is not defined

In [ ]:
# astype
## 데이터 타입을 변경
arr = np.array([1, 2, 3, 4, 5, 6])
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5. 6.]


In [ ]:
#   ravel
## 다차원 배열을 1차원 배열로 변경
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshaped((2, 3))
print(reshaped)

raveled = reshaped.ravel()
print(raveled)



AttributeError: 'numpy.ndarray' object has no attribute 'reshaped'

In [13]:
# flaten#
## 다차원배열을 1차원 배열로 변경

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)
flattend = arr.flatten()
print(flattend)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [14]:
# transpose
## 배열의 축을 바꾸는 함수

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed = arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [17]:
# 수학연산
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2) # Numpy에서는 리스트 합치기가 아닌 더하기가 된다
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [ ]:
# 배열 간 요소 비교 연산
arr1 = np.array([5, 3, 3])
arr2 = np.array([1, 2, 6])

print(arr1 < arr2)
print(arr1 > arr2)

[False False  True]
[ True  True False]


In [ ]:
# 배열 간의 논리 연산
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])

print(arr1 & arr2)
print(arr1 | arr2)

[False False  True]
[ True  True  True]


In [23]:
# 배열 간의 집계 연산
arr = np.array([1, 2, 3, 4, 5])

print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())

15
3.0
1
5


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
scalar = 2
print(scalar)